insert into public.artists (slug, name, state, city, region, styles, mediums, bio, story, verified, published, approval_status, submitted_at, approved_at) values
('ananya-jha', 'Ananya Jha', 'Bihar', 'Madhubani', 'Mithila', array['Madhubani','Natural pigment','Linework'], array['Traditional','Painting','Handmade'], 'A Mithila painter building contemporary compositions from folk memory, festivals, and courtyard rituals.', 'Ananya learned linework from her grandmother and now documents everyday rituals in a quieter modern palette.', true, true, 'approved', now() - interval '30 days', now() - interval '28 days'),
('ramesh-varkhade', 'Ramesh Varkhade', 'Maharashtra', 'Dahanu', 'Konkan', array['Warli','Community murals','Ritual forms'], array['Traditional','Painting'], 'A Warli artist translating village gatherings, harvest, and music into spare rhythmic compositions.', 'Ramesh paints with rice-paste-inspired geometry and teaches younger artists how to build movement with the simplest marks.', true, true, 'approved', now() - interval '29 days', now() - interval '27 days'),
('meera-markam', 'Meera Markam', 'Madhya Pradesh', 'Mandla', 'Gondwana', array['Gond','Wildlife','Dot pattern'], array['Traditional','Digital','Painting'], 'A Gond-inspired illustrator drawing forests, birds, and memory maps with patient dotted textures.', 'Meera works between acrylic studies and digital translations, keeping the energy of hand-built dots visible in both.', false, true, 'approved', now() - interval '28 days', now() - interval '26 days'),
('subhasis-padhi', 'Subhasis Padhi', 'Odisha', 'Raghurajpur', 'Puri', array['Pattachitra','Mythic panels','Palm leaf'], array['Traditional','Handmade','Painting'], 'A Pattachitra maker focused on narrative panels, scroll rhythm, and temple-town detail.', 'Subhasis builds each work as a story sequence, balancing devotional iconography with contemporary collectors wall scale.', true, true, 'approved', now() - interval '27 days', now() - interval '25 days'),
('kavya-narayanan', 'Kavya Narayanan', 'Tamil Nadu', 'Thanjavur', 'Cauvery delta', array['Tanjore','Gold relief','Devotional portraiture'], array['Traditional','Painting','Handmade'], 'A Tanjore artist pairing gold relief traditions with intimate portrait studies.', 'Kavya works slowly with layered surfaces, recording how shine changes through the day before final varnishing.', true, true, 'approved', now() - interval '26 days', now() - interval '24 days'),
('nafisa-qureshi', 'Nafisa Qureshi', 'Andhra Pradesh', 'Srikalahasti', 'Rayalaseema', array['Kalamkari','Botanical drawing','Textile art'], array['Textile','Handmade','Traditional'], 'A Kalamkari textile artist exploring botanical stories through hand-drawn cloth panels.', 'Nafisa studies old garden drawings and market flowers, then translates them into cloth pieces with patient linework.', false, true, 'approved', now() - interval '25 days', now() - interval '23 days'),
('gurleen-kaur', 'Gurleen Kaur', 'Punjab', 'Patiala', 'Malwa', array['Phulkari','Embroidery','Textile memory'], array['Textile','Handmade'], 'A Phulkari maker composing heirloom embroidery into wearable and framed textile works.', 'Gurleen documents stitches from family wardrobes and rebuilds them as bright, contemporary textile maps.', true, true, 'approved', now() - interval '24 days', now() - interval '22 days'),
('devansh-somani', 'Devansh Somani', 'Rajasthan', 'Jaipur', 'Shekhawati', array['Block printing','Miniature painting','Pattern systems'], array['Digital','Textile','Painting'], 'A digital illustrator and block-print researcher building repeat patterns from Rajasthani motifs.', 'Devansh prototypes on tablet, carves selected motifs, and compares digital rhythm with hand-printed irregularity.', false, true, 'approved', now() - interval '23 days', now() - interval '21 days'),
('aditi-banerjee', 'Aditi Banerjee', 'West Bengal', 'Kolkata', 'Bengal', array['Kantha','Textile storytelling','Thread drawing'], array['Textile','Handmade'], 'A textile artist turning family stories and small domestic scenes into quiet stitched panels.', 'Aditi began with old sari fragments and now builds sample panels around migration, household memory, and women’s work.', false, false, 'pending_approval', now() - interval '2 days', null),
('faizan-lone', 'Faizan Lone', 'Jammu and Kashmir', 'Srinagar', 'Kashmir Valley', array['Papier mache','Floral ornament','Surface pattern'], array['Handmade','Painting'], 'A surface artist studying papier mache ornament through small floral sample boards.', 'Faizan submitted an early profile with promising samples, but the application needs clearer artwork attribution before approval.', false, false, 'rejected', now() - interval '6 days', null)
on conflict (slug) do nothing;

insert into public.artworks (artist_id, slug, title, category, style, state, description, cultural_context, price_inr, price_on_request, is_featured)
select id, 'courtyard-fish-song', 'Courtyard Fish Song', 'Original', 'Madhubani', 'Bihar', 'A balanced Mithila composition of fish, leaves, and women gathered near a monsoon courtyard.', 'Fish motifs in Mithila painting often carry fertility, abundance, and river memory.', 28000, false, true from public.artists where slug = 'ananya-jha'
union all select id, 'sita-garden-sketch', 'Sita Garden Sketch', 'Print', 'Madhubani', 'Bihar', 'A smaller study translating folk narrative into a green garden rhythm.', 'The piece borrows from household storytelling traditions without depicting a single fixed scene.', 4200, false, false from public.artists where slug = 'ananya-jha'
union all select id, 'night-harvest-circle', 'Night Harvest Circle', 'Original', 'Warli', 'Maharashtra', 'A moonlit circular dance painted with spare village geometry.', 'Warli compositions often turn communal work and celebration into a shared visual rhythm.', 18000, false, true from public.artists where slug = 'ramesh-varkhade'
union all select id, 'monsoon-drumline', 'Monsoon Drumline', 'Handmade', 'Warli', 'Maharashtra', 'A long-format piece made for a hallway, full of dancers and drummers.', 'The repeated figures reference seasonal gathering and oral performance.', null, true, false from public.artists where slug = 'ramesh-varkhade'
union all select id, 'sal-tree-breathing', 'Sal Tree Breathing', 'Digital art', 'Gond', 'Madhya Pradesh', 'A digital study of a living sal tree built from thousands of hand-placed dots.', 'Gond-inspired visual language often treats forest life as animated and relational.', 9000, false, true from public.artists where slug = 'meera-markam'
union all select id, 'hornbill-map', 'Hornbill Map', 'Print', 'Gond', 'Madhya Pradesh', 'A bird form carrying a pattern-map of streams and seeds.', 'The work uses wildlife as a way to remember paths through forest villages.', 5200, false, false from public.artists where slug = 'meera-markam'
union all select id, 'jagannath-rath-study', 'Jagannath Rath Study', 'Original', 'Pattachitra', 'Odisha', 'A compact narrative panel inspired by the movement of the Rath Yatra.', 'Pattachitra paintings from Odisha are known for story panels, firm linework, and devotional detail.', 36000, false, true from public.artists where slug = 'subhasis-padhi'
union all select id, 'palm-leaf-quiet', 'Palm Leaf Quiet', 'Handmade', 'Pattachitra', 'Odisha', 'An intimate palm-leaf-inspired study with small repeating borders.', 'The format nods to manuscript craft and devotional storytelling traditions.', null, true, false from public.artists where slug = 'subhasis-padhi'
union all select id, 'golden-veena-study', 'Golden Veena Study', 'Original', 'Tanjore', 'Tamil Nadu', 'A luminous study of music, gold relief, and devotional stillness.', 'Tanjore painting is recognized for rich surfaces, relief work, and gold-toned detail.', 62000, false, true from public.artists where slug = 'kavya-narayanan'
union all select id, 'lamp-at-dusk', 'Lamp at Dusk', 'Original', 'Tanjore', 'Tamil Nadu', 'A smaller gold-accented panel for collectors starting with Tanjore work.', 'The lamp motif references evening ritual and the changing shine of gold leaf.', 24000, false, false from public.artists where slug = 'kavya-narayanan'
union all select id, 'indigo-garden-cloth', 'Indigo Garden Cloth', 'Handmade', 'Kalamkari', 'Telangana', 'A hand-drawn textile panel of leaves, seed pods, and small birds.', 'Kalamkari traditions use pen-drawn cloth storytelling and botanical or narrative detail.', 15000, false, false from public.artists where slug = 'nafisa-qureshi'
union all select id, 'market-flower-border', 'Market Flower Border', 'Print', 'Kalamkari', 'Telangana', 'A border study inspired by flower sellers around Charminar.', 'The work translates a living city scene into a textile pattern language.', 3800, false, false from public.artists where slug = 'nafisa-qureshi'
union all select id, 'gulabi-field-stitch', 'Gulabi Field Stitch', 'Handmade', 'Phulkari', 'Punjab', 'A bright embroidered panel arranged like a remembered field boundary.', 'Phulkari work is deeply connected to domestic textiles, gifting, and regional memory.', 19500, false, true from public.artists where slug = 'gurleen-kaur'
union all select id, 'patiala-archive-piece', 'Patiala Archive Piece', 'Original', 'Phulkari', 'Punjab', 'A stitched archive panel built from motifs found in family textiles.', 'The work studies how inherited stitches can become contemporary wall pieces.', null, true, false from public.artists where slug = 'gurleen-kaur'
union all select id, 'desert-repeat-one', 'Desert Repeat One', 'Digital art', 'Block Printing', 'Rajasthan', 'A repeat pattern prototype inspired by carved blocks and desert shrubs.', 'Block printing in Rajasthan carries a long relationship between motif, dye, and cloth trade.', 7000, false, false from public.artists where slug = 'devansh-somani'
union all select id, 'blue-pottery-morning', 'Blue Pottery Morning', 'Print', 'Blue pottery', 'Rajasthan', 'A Jaipur blue pottery pattern interpreted as a flat digital poster.', 'The blue and white language references ceramic craft without copying a specific historical tile.', 3200, false, false from public.artists where slug = 'devansh-somani'
union all select id, 'miniature-monsoon-window', 'Miniature Monsoon Window', 'Digital art', 'Miniature painting', 'Rajasthan', 'A digital miniature-inspired window scene with restrained detail.', 'The composition studies scale, architecture, and mood from miniature painting traditions.', 8800, false, false from public.artists where slug = 'devansh-somani'
union all select id, 'green-mithila-birds', 'Green Mithila Birds', 'Original', 'Madhubani', 'Bihar', 'A bird pair study made with a calmer forest palette.', 'Birds in folk paintings often carry ideas of companionship, travel, and seasonal return.', null, true, false from public.artists where slug = 'ananya-jha'
union all select id, 'village-procession-study', 'Village Procession Study', 'Print', 'Warli', 'Maharashtra', 'A study of movement, animals, and music in a horizontal procession.', 'The minimal figures point toward shared village activity rather than individual portraiture.', 2800, false, false from public.artists where slug = 'ramesh-varkhade'
union all select id, 'forest-listening-post', 'Forest Listening Post', 'Digital art', 'Gond', 'Madhya Pradesh', 'A digital composition where leaves, animal tracks, and wind marks share a frame.', 'The piece uses forest motifs as active presences rather than scenic background.', null, true, false from public.artists where slug = 'meera-markam'
on conflict (slug) do nothing;

insert into public.posts (artist_id, artwork_id, body, tags)
select a.id, w.id, 'Testing a softer green border before I fill the fish scales. The quiet part of the painting always arrives first.', array['process','madhubani','natural-pigment'] from public.artists a join public.artworks w on w.slug = 'green-mithila-birds' where a.slug = 'ananya-jha'
union all select a.id, w.id, 'Todays mural sketch is all rhythm. I am trying to keep the dancers light but the circle strong.', array['warli','wip','murals'] from public.artists a join public.artworks w on w.slug = 'night-harvest-circle' where a.slug = 'ramesh-varkhade'
union all select a.id, w.id, 'Dot layer three. I like when the bird starts looking like it is listening back.', array['gond','digital','wildlife'] from public.artists a join public.artworks w on w.slug = 'hornbill-map' where a.slug = 'meera-markam'
union all select a.id, w.id, 'Border studies from this morning. The small mistakes are showing me where the scroll wants to breathe.', array['pattachitra','story-panel'] from public.artists a join public.artworks w on w.slug = 'palm-leaf-quiet' where a.slug = 'subhasis-padhi'
union all select a.id, w.id, 'Gold catches the room differently after sunset. Keeping this one under a lamp for the final checks.', array['tanjore','gold-work'] from public.artists a join public.artworks w on w.slug = 'lamp-at-dusk' where a.slug = 'kavya-narayanan'
union all select a.id, w.id, 'The flower border is becoming more Hyderabad than I expected. That is usually a good sign.', array['kalamkari','textile','botanical'] from public.artists a join public.artworks w on w.slug = 'market-flower-border' where a.slug = 'nafisa-qureshi'
union all select a.id, w.id, 'Archiving an old stitch from my nanis dupatta before adapting it for a framed panel.', array['phulkari','archive','stitching'] from public.artists a join public.artworks w on w.slug = 'patiala-archive-piece' where a.slug = 'gurleen-kaur'
union all select a.id, w.id, 'Tablet sketch to carved block test. Digital repeat is perfect, block print is alive.', array['block-printing','digital','pattern'] from public.artists a join public.artworks w on w.slug = 'desert-repeat-one' where a.slug = 'devansh-somani';

insert into public.regional_art_forms (slug, name, state, medium, cultural_context, featured_artist_names) values
('madhubani', 'Madhubani', 'Bihar', 'Painting', 'A Mithila tradition known for dense linework, symbolic motifs, natural pigment memory, and domestic storytelling.', array['Ananya Jha']),
('warli', 'Warli', 'Maharashtra', 'Painting', 'A visual language of circles, triangles, and community scenes rooted in village life and ritual gatherings.', array['Ramesh Varkhade']),
('gond', 'Gond', 'Madhya Pradesh', 'Painting and digital', 'A forest-rich storytelling form where animals, trees, and spirits are often built through dots and pattern.', array['Meera Markam']),
('pattachitra', 'Pattachitra', 'Odisha', 'Painting', 'Narrative cloth and scroll painting with firm linework, devotional scenes, and carefully structured borders.', array['Subhasis Padhi']),
('tanjore', 'Tanjore', 'Tamil Nadu', 'Painting', 'A luminous tradition known for devotional figures, relief work, and gold-toned surfaces.', array['Kavya Narayanan']),
('kalamkari', 'Kalamkari', 'Telangana', 'Textile', 'Pen-drawn cloth work shaped by botanical detail, storytelling panels, and patient hand processes.', array['Nafisa Qureshi']),
('phulkari', 'Phulkari', 'Punjab', 'Textile', 'A vibrant embroidery tradition connected to family textiles, gifting, memory, and fields of color.', array['Gurleen Kaur']),
('block-printing', 'Block Printing', 'Rajasthan', 'Textile', 'A carved-block textile practice where motif, dye, hand pressure, and repetition create living pattern.', array['Devansh Somani'])
on conflict (slug) do nothing;

insert into public.workshops (artist_id, title, art_form, format, access, starts_at, description)
select id, 'Madhubani Borders for Beginners', 'Madhubani', 'Live', 'Free', '2026-06-15 18:00:00+05:30', 'Build border discipline with leaves, fish, and line repetition.' from public.artists where slug = 'ananya-jha'
union all select id, 'Warli Movement and Figure Rhythm', 'Warli', 'Recorded', 'Free', null, 'A compact recorded class on making simple figures feel alive.' from public.artists where slug = 'ramesh-varkhade'
union all select id, 'Gond-Inspired Digital Brushes', 'Gond', 'Live', 'Ticketed', '2026-06-22 19:30:00+05:30', 'Translate hand-dot rhythm into digital illustration without losing warmth.' from public.artists where slug = 'meera-markam'
union all select id, 'Pattachitra Story Panel Planning', 'Pattachitra', 'Live', 'Ticketed', '2026-06-29 17:00:00+05:30', 'Plan a small narrative panel with borders, sequence, and focal icons.' from public.artists where slug = 'subhasis-padhi'
union all select id, 'Gold Relief Care for Tanjore Work', 'Tanjore', 'Recorded', 'Ticketed', null, 'A careful class on surface preparation, shine, and collector handling.' from public.artists where slug = 'kavya-narayanan'
union all select id, 'Phulkari Motif Archive', 'Phulkari', 'Live', 'Free', '2026-07-04 16:00:00+05:30', 'Document family textile motifs and turn them into a simple stitch chart.' from public.artists where slug = 'gurleen-kaur';

insert into public.challenges (title, prize_details, submission_deadline, description) values
('Monsoon Memory Challenge', 'Featured homepage showcase and collector newsletter spotlight', '2026-07-12', 'Submit one artwork or process post that interprets rain, waiting, soil, or seasonal return.');

insert into public.grants (title, grant_type, prize_details, deadline, description) values
('Emerging Regional Artist Microgrant', 'Grant', 'INR 25,000 material support for three selected artists', '2026-08-02', 'For early-career artists working with traditional, digital, textile, or handmade Indian art practices.'),
('Handmade Packaging Motif Call', 'Collaboration', 'Paid brand collaboration shortlist', '2026-06-30', 'A regional craft studio is looking for original motif systems inspired by forest, soil, and local festivals.');

insert into public.ads (sponsor, title, copy, placement) values
('Studio Paper Co.', 'Cold-pressed papers for Indian artists', 'Archival sheets, handmade texture, and small-batch sketchbooks for process-heavy work.', 'homepage'),
('Sutradhar Frames', 'Quiet framing for textile and paper works', 'Museum-grade framing options designed for delicate handmade surfaces.', 'feed'),
('Rang Studio', 'Natural pigment starter kits', 'Earthy color kits for workshops, students, and artists testing traditional palettes.', 'artwork');
